CREATE TABLE Autores (
	ID_Autor INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nombre_Apellido VARCHAR(50) NOT NULL,
);

CREATE TABLE Libros (
	ID_Libro INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Titulo VARCHAR(50) NOT NULL,
	ID_Autor INT NOT NULL,
	Año_Publicacion INT NOT NULL,
	FOREIGN KEY (ID_Autor) REFERENCES Autores (ID_Autor)
);

CREATE TABLE Prestamos (
	ID_Prestamo INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_Libro INT NOT NULL,
	Fecha_Prestamo DATETIME NOT NULL,
	Fecha_Devolucion DATETIME NOT NULL,
	FOREIGN KEY (ID_Libro) REFERENCES Libros (ID_Libro)
);